package io.sandbox.user_state;

public enum UserState {

    STATE_START_REQUEST,
    STATE_START_RESPONSE,
    STATE_PORTFOLIO,
    STATE_POST_ORDER_REQUEST,
    STATE_POST_ORDER_OPERATION_TYPE,
    STATE_POST_ORDER_RESPONSE,
    STATE_OPERATIONS,
    STATE_COMPANY_DATA_REQUEST,
    STATE_COMPANY_DATA_RESPONSE,
    STATE_DEFAULT
}
